
:comment: 'color: #005; font-style: italic;'
:keyword: 'color: #A00; font-weight: bold;'
:method: 'color: #077;'
:class: 'color: #074;'
:module: 'color: #050;'
:punct: 'color: #447; font-weight: bold;'
:symbol: 'color: #099;'
:string: 'color: #944;'
:char: 'color: #F07;'
:ident: 'color: #004;'
:constant: 'color: #07F;'
:regex: 'color: #B66;'
:number: 'color: #F99;'
:attribute: 'color: #5bb;'
:global: 'color: #7FB;'
:expr: 'color: #227;'
:escape: 'color: #277;'
:add: 'background: yellow;'
:del: 'background: red;'
:background: "font-size:13px;background-color:#f1f1f3;color: #112;"
